heat_template_version: 2015-04-30

description: Template to deploy an OpenStack instance

parameters:
  image_id:
    type: string
    description: ID or name of the image to use for the instance
  flavor_id:
    type: string
    description: Flavor to use for the instance
  network_id:
    type: string
    description: Network ID for the server port

resources:
  instance:
    type: OS::Nova::Server
    properties:
      key_name: goryunov
      image: { get_param: image_id }
      flavor: { get_param: flavor_id }
      networks:
        - port: { get_resource: server_port }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: network_id }