- name: Deploy application stack
  hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - openjdk-17-jre
          - docker.io
          - jq
          - curl
        state: present
        update_cache: yes

    - name: Get the latest Docker Compose version
      shell: |
        curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name
      register: compose_version

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version.stdout }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/bin/docker-compose
        mode: '0755'

    - name: Create symlink for Docker Compose
      file:
        src: /usr/bin/docker-compose
        dest: /usr/local/bin/docker-compose
        state: link

    - name: Verify Docker installation
      command: docker --version

    - name: Verify Docker Compose installation
      command: docker-compose --version